#!/usr/bin/env python3
"""
Spanish vocabulary dictionary for learning material analysis.
스페인어 학습 자료 분석용 어휘 사전
"""

# 난이도별 핵심 어휘 사전
SPANISH_VOCABULARY = {
    # 정치/사회 관련 어휘 (C1 수준)
    'gobierno': '정부',
    'política': '정치',
    'democracia': '민주주의',
    'elecciones': '선거',
    'presidente': '대통령',
    'ministro': '장관',
    'parlamento': '의회',
    'congreso': '국회',
    'senado': '상원',
    'diputado': '하원의원',
    'partido': '정당',
    'oposición': '야당',
    'coalición': '연정',
    'reforma': '개혁',
    'ley': '법률',
    'constitución': '헌법',
    'justicia': '정의',
    'tribunal': '법원',
    'juez': '판사',
    'fiscal': '검사',
    'corrupción': '부패',
    'transparencia': '투명성',
    'ciudadano': '시민',
    'derechos': '권리',
    'libertad': '자유',
    'igualdad': '평등',
    'sociedad': '사회',
    'comunidad': '공동체',
    'público': '공공의',
    'privado': '사적인',
    'manifestación': '시위',
    'protesta': '항의',
    'huelga': '파업',
    'sindicato': '노동조합',
    'trabajador': '노동자',
    'empleo': '고용',
    'desempleo': '실업',
    'crisis': '위기',
    'economía': '경제',
    'mercado': '시장',
    'empresa': '기업',
    'negocio': '사업',
    'comercio': '상업',
    'industria': '산업',
    'agricultura': '농업',
    'turismo': '관광업',
    'tecnología': '기술',
    'innovación': '혁신',
    'desarrollo': '발전',
    'crecimiento': '성장',
    'inversión': '투자',
    'presupuesto': '예산',
    'impuesto': '세금',
    'deuda': '부채',
    'déficit': '적자',
    'inflación': '인플레이션',
    'recesión': '불황',
    
    # 국제/외교 관련 어휘 (C1 수준)
    'internacional': '국제적인',
    'diplomacia': '외교',
    'embajada': '대사관',
    'embajador': '대사',
    'acuerdo': '협정',
    'tratado': '조약',
    'pacto': '협약',
    'alianza': '동맹',
    'cooperación': '협력',
    'conflicto': '갈등',
    'guerra': '전쟁',
    'paz': '평화',
    'seguridad': '안보',
    'defensa': '국방',
    'militar': '군사의',
    'ejército': '군대',
    'terrorismo': '테러리즘',
    'inmigración': '이민',
    'refugiado': '난민',
    'frontera': '국경',
    'visa': '비자',
    'pasaporte': '여권',
    'ciudadanía': '시민권',
    'extranjero': '외국인',
    'europeo': '유럽의',
    'americano': '미국의',
    'asiático': '아시아의',
    'africano': '아프리카의',
    'mundial': '세계적인',
    'global': '글로벌한',
    'regional': '지역의',
    'nacional': '국가의',
    'local': '지역의',
    
    # 사회/문화 관련 어휘 (B2 수준)
    'educación': '교육',
    'universidad': '대학교',
    'estudiante': '학생',
    'profesor': '교수',
    'maestro': '선생님',
    'escuela': '학교',
    'colegio': '학교',
    'instituto': '연구소',
    'biblioteca': '도서관',
    'museo': '박물관',
    'teatro': '극장',
    'cine': '영화관',
    'película': '영화',
    'libro': '책',
    'revista': '잡지',
    'periódico': '신문',
    'noticia': '뉴스',
    'información': '정보',
    'comunicación': '소통',
    'medio': '매체',
    'internet': '인터넷',
    'móvil': '휴대폰',
    'ordenador': '컴퓨터',
    'aplicación': '어플리케이션',
    'programa': '프로그램',
    'sistema': '시스템',
    'red': '네트워크',
    'datos': '데이터',
    'archivo': '파일',
    'documento': '문서',
    'imagen': '이미지',
    'video': '비디오',
    'audio': '오디오',
    'música': '음악',
    'canción': '노래',
    'artista': '예술가',
    'pintor': '화가',
    'escritor': '작가',
    'poeta': '시인',
    'cultura': '문화',
    'tradición': '전통',
    'costumbre': '관습',
    'festival': '축제',
    'celebración': '축하',
    'ceremonia': '의식',
    'religión': '종교',
    'iglesia': '교회',
    'católico': '가톨릭의',
    'cristiano': '기독교의',
    'judío': '유대교의',
    'musulmán': '이슬람의',
    'budista': '불교의',
    
    # 건강/의료 관련 어휘 (B2 수준)
    'salud': '건강',
    'medicina': '의학',
    'médico': '의사',
    'doctor': '박사',
    'enfermero': '간호사',
    'hospital': '병원',
    'clínica': '클리닉',
    'farmacia': '약국',
    'medicamento': '약',
    'pastilla': '알약',
    'receta': '처방전',
    'tratamiento': '치료',
    'operación': '수술',
    'cirugía': '외과',
    'paciente': '환자',
    'enfermedad': '질병',
    'síntoma': '증상',
    'dolor': '통증',
    'fiebre': '열',
    'gripe': '독감',
    'resfriado': '감기',
    'tos': '기침',
    'dolor de cabeza': '두통',
    'náuseas': '메스꺼움',
    'vómito': '구토',
    'diarrea': '설사',
    'estreñimiento': '변비',
    'alergia': '알레르기',
    'diabetes': '당뇨병',
    'cáncer': '암',
    'corazón': '심장',
    'pulmón': '폐',
    'estómago': '위',
    'hígado': '간',
    'riñón': '신장',
    'cerebro': '뇌',
    'sangre': '혈액',
    'presión': '혈압',
    'análisis': '검사',
    'radiografía': '엑스레이',
    'vacuna': '백신',
    'prevención': '예방',
    
    # 환경/과학 관련 어휘 (B2-C1 수준)
    'medio ambiente': '환경',
    'naturaleza': '자연',
    'ecología': '생태학',
    'ecosistema': '생태계',
    'biodiversidad': '생물다양성',
    'cambio climático': '기후변화',
    'calentamiento global': '지구온난화',
    'contaminación': '오염',
    'basura': '쓰레기',
    'residuo': '폐기물',
    'reciclaje': '재활용',
    'energía': '에너지',
    'renovable': '재생가능한',
    'solar': '태양의',
    'eólica': '풍력의',
    'nuclear': '핵의',
    'carbón': '석탄',
    'petróleo': '석유',
    'gas': '가스',
    'electricidad': '전기',
    'agua': '물',
    'aire': '공기',
    'tierra': '땅',
    'mar': '바다',
    'océano': '대양',
    'río': '강',
    'lago': '호수',
    'montaña': '산',
    'bosque': '숲',
    'selva': '정글',
    'desierto': '사막',
    'playa': '해변',
    'isla': '섬',
    'continente': '대륙',
    'país': '국가',
    'ciudad': '도시',
    'pueblo': '마을',
    'campo': '시골',
    'agricultura': '농업',
    'ganadería': '축산업',
    'pesca': '어업',
    'animal': '동물',
    'planta': '식물',
    'árbol': '나무',
    'flor': '꽃',
    'fruta': '과일',
    'verdura': '채소',
    
    # 일상생활 관련 어휘 (B1-B2 수준)
    'familia': '가족',
    'padre': '아버지',
    'madre': '어머니',
    'hijo': '아들',
    'hija': '딸',
    'hermano': '형제',
    'hermana': '자매',
    'abuelo': '할아버지',
    'abuela': '할머니',
    'tío': '삼촌',
    'tía': '이모',
    'primo': '사촌',
    'esposo': '남편',
    'esposa': '아내',
    'matrimonio': '결혼',
    'boda': '결혼식',
    'divorcio': '이혼',
    'casa': '집',
    'hogar': '가정',
    'apartamento': '아파트',
    'piso': '층',
    'habitación': '방',
    'cocina': '부엌',
    'baño': '화장실',
    'sala': '거실',
    'comedor': '식당',
    'jardín': '정원',
    'mueble': '가구',
    'mesa': '테이블',
    'silla': '의자',
    'cama': '침대',
    'sofá': '소파',
    'televisión': '텔레비전',
    'radio': '라디오',
    'teléfono': '전화',
    'ropa': '옷',
    'camisa': '셔츠',
    'pantalón': '바지',
    'vestido': '드레스',
    'zapato': '신발',
    'comida': '음식',
    'desayuno': '아침식사',
    'almuerzo': '점심식사',
    'cena': '저녁식사',
    'restaurante': '식당',
    'café': '카페',
    'bar': '바',
    'supermercado': '슈퍼마켓',
    'tienda': '가게',
    'mercado': '시장',
    'dinero': '돈',
    'precio': '가격',
    'barato': '싼',
    'caro': '비싼',
    'comprar': '사다',
    'vender': '팔다',
    'pagar': '지불하다',
    'trabajo': '일',
    'oficina': '사무실',
    'jefe': '상사',
    'empleado': '직원',
    'sueldo': '급여',
    'vacaciones': '휴가',
    'tiempo libre': '자유시간',
    'deporte': '스포츠',
    'fútbol': '축구',
    'tenis': '테니스',
    'natación': '수영',
    'gimnasio': '체육관',
    'parque': '공원',
    'viaje': '여행',
    'turista': '관광객',
    'hotel': '호텔',
    'avión': '비행기',
    'tren': '기차',
    'autobús': '버스',
    'coche': '자동차',
    'bicicleta': '자전거',
    'metro': '지하철',
    
    # 감정/성격 관련 어휘 (B1-B2 수준)
    'feliz': '행복한',
    'alegre': '기쁜',
    'contento': '만족한',
    'triste': '슬픈',
    'preocupado': '걱정하는',
    'nervioso': '긴장한',
    'tranquilo': '차분한',
    'relajado': '편안한',
    'cansado': '피곤한',
    'estresado': '스트레스받는',
    'enojado': '화난',
    'furioso': '격분한',
    'sorprendido': '놀란',
    'emocionado': '흥분한',
    'aburrido': '지루한',
    'divertido': '재미있는',
    'interesante': '흥미로운',
    'importante': '중요한',
    'necesario': '필요한',
    'útil': '유용한',
    'fácil': '쉬운',
    'difícil': '어려운',
    'posible': '가능한',
    'imposible': '불가능한',
    'seguro': '확실한',
    'dudoso': '의심스러운',
    'claro': '명확한',
    'confuso': '혼란스러운',
    'simple': '간단한',
    'complicado': '복잡한',
    'rápido': '빠른',
    'lento': '느린',
    'grande': '큰',
    'pequeño': '작은',
    'nuevo': '새로운',
    'viejo': '오래된',
    'joven': '젊은',
    'mayor': '더 큰',
    'menor': '더 작은',
    'mejor': '더 좋은',
    'peor': '더 나쁜',
    'bueno': '좋은',
    'malo': '나쁜',
    'bonito': '예쁜',
    'feo': '못생긴',
    'rico': '부유한',
    'pobre': '가난한',
    
    # 동사 (B1-B2 수준)
    'ser': '이다',
    'estar': '있다',
    'tener': '갖다',
    'hacer': '하다',
    'decir': '말하다',
    'ir': '가다',
    'venir': '오다',
    'llegar': '도착하다',
    'salir': '나가다',
    'entrar': '들어가다',
    'subir': '올라가다',
    'bajar': '내려가다',
    'caminar': '걷다',
    'correr': '뛰다',
    'volar': '날다',
    'nadar': '수영하다',
    'dormir': '자다',
    'despertar': '깨다',
    'levantarse': '일어나다',
    'sentarse': '앉다',
    'acostarse': '눕다',
    'comer': '먹다',
    'beber': '마시다',
    'cocinar': '요리하다',
    'lavar': '씻다',
    'limpiar': '청소하다',
    'estudiar': '공부하다',
    'aprender': '배우다',
    'enseñar': '가르치다',
    'leer': '읽다',
    'escribir': '쓰다',
    'hablar': '말하다',
    'escuchar': '듣다',
    'ver': '보다',
    'mirar': '바라보다',
    'buscar': '찾다',
    'encontrar': '발견하다',
    'perder': '잃다',
    'ganar': '이기다',
    'jugar': '놀다',
    'trabajar': '일하다',
    'vivir': '살다',
    'morir': '죽다',
    'nacer': '태어나다',
    'crecer': '자라다',
    'cambiar': '바꾸다',
    'mejorar': '개선하다',
    'empeorar': '악화시키다',
    'ayudar': '돕다',
    'colaborar': '협력하다',
    'participar': '참여하다',
    'contribuir': '기여하다',
    'compartir': '공유하다',
    'distribuir': '배포하다',
    'entregar': '전달하다',
    'recibir': '받다',
    'obtener': '얻다',
    'ganar': '이기다, 벌다',
    'perder': '잃다',
    'faltar': '부족하다',
    'necesitar': '필요하다',
    'querer': '원하다',
    'desear': '바라다',
    'esperar': '기다리다, 바라다',
    'intentar': '시도하다',
    'tratar': '다루다, 노력하다',
    'empezar': '시작하다',
    'comenzar': '시작하다',
    'iniciar': '시작하다',
    'terminar': '끝내다',
    'acabar': '끝내다',
    'finalizar': '마무리하다',
    'completar': '완성하다',
    'cumplir': '이행하다',
    'formar': '형성하다',
    'construir': '건설하다',
    'destruir': '파괴하다',
    'romper': '부수다',
    'cortar': '자르다',
    'unir': '합치다',
    'separar': '분리하다',
    'dividir': '나누다',
    'multiplicar': '곱하다',
    'sumar': '더하다',
    'restar': '빼다',
    'calcular': '계산하다',
    'medir': '측정하다',
    'pesar': '무게를 재다',
    'comparar': '비교하다',
    'relacionar': '관련시키다',
    'conectar': '연결하다',
    'comunicar': '소통하다',
    'contactar': '연락하다',
    'llamar': '부르다',
    'preguntar': '묻다',
    'responder': '답하다',
    'contestar': '답하다',
    'solucionar': '해결하다',
    'arreglar': '고치다',
    'reparar': '수리하다',
    'funcionar': '작동하다',
    'operar': '운영하다',
    'manejar': '다루다',
    'controlar': '제어하다',
    'dirigir': '지시하다',
    'mandar': '명령하다',
    'obedecer': '복종하다',
    'seguir': '따르다',
    'guiar': '안내하다',
    'llevar': '가지고 가다',
    'traer': '가져오다',
    'enviar': '보내다',
    'mandar': '보내다',
    'recibir': '받다',
    'coger': '잡다',
    'tomar': '잡다, 마시다',
    'dar': '주다',
    'poner': '놓다',
    'quitar': '제거하다',
    'sacar': '꺼내다',
    'meter': '넣다',
    'abrir': '열다',
    'cerrar': '닫다',
    'encender': '켜다',
    'apagar': '끄다',
    'subir': '올리다',
    'bajar': '내리다',
    'levantar': '들어올리다',
    'caer': '떨어지다',
    'tirar': '던지다',
    'coger': '받다',
    'golpear': '치다',
    'tocar': '만지다',
    'abrazar': '포옹하다',
    'besar': '키스하다',
    'sonreír': '미소짓다',
    'reír': '웃다',
    'llorar': '울다',
    'gritar': '소리치다',
    'susurrar': '속삭이다',
    'cantar': '노래하다',
    'bailar': '춤추다',
    'tocar': '연주하다',
    'dibujar': '그리다',
    'pintar': '칠하다',
    'fotografiar': '사진찍다',
    'filmar': '촬영하다',
    'grabar': '녹음하다',
    'recordar': '기억하다',
    'olvidar': '잊다',
    'pensar': '생각하다',
    'reflexionar': '반성하다',
    'imaginar': '상상하다',
    'soñar': '꿈꾸다',
    'creer': '믿다',
    'dudar': '의심하다',
    'saber': '알다',
    'conocer': '알다',
    'entender': '이해하다',
    'comprender': '이해하다',
    'explicar': '설명하다',
    'aclarar': '명확히 하다',
    'demostrar': '증명하다',
    'probar': '증명하다',
    'mostrar': '보여주다',
    'enseñar': '보여주다',
    'indicar': '지시하다',
    'señalar': '가리키다',
    'marcar': '표시하다',
    'elegir': '선택하다',
    'escoger': '고르다',
    'decidir': '결정하다',
    'preferir': '선호하다',
    'gustar': '좋아하다',
    'amar': '사랑하다',
    'odiar': '미워하다',
    'molestar': '귀찮게 하다',
    'preocupar': '걱정시키다',
    'tranquilizar': '안심시키다',
    'calmar': '진정시키다',
    'excitar': '흥분시키다',
    'aburrir': '지루하게 하다',
    'divertir': '즐겁게 하다',
    'entretener': '오락하게 하다',
    'sorprender': '놀라게 하다',
    'asustar': '무섭게 하다',
    'proteger': '보호하다',
    'cuidar': '돌보다',
    'vigilar': '감시하다',
    'observar': '관찰하다',
    'notar': '알아차리다',
    'darse cuenta': '깨닫다',
    'advertir': '경고하다',
    'avisar': '알리다',
    'informar': '알리다',
    'anunciar': '발표하다',
    'declarar': '선언하다',
    'afirmar': '확언하다',
    'negar': '부정하다',
    'rechazar': '거부하다',
    'aceptar': '받아들이다',
    'aprobar': '승인하다',
    'permitir': '허용하다',
    'prohibir': '금지하다',
    'impedir': '방해하다',
    'evitar': '피하다',
    'escapar': '탈출하다',
    'huir': '도망가다',
    'perseguir': '추적하다',
    'seguir': '따라가다',
    'acompañar': '동반하다',
    'invitar': '초대하다',
    'visitar': '방문하다',
    'recibir': '맞이하다',
    'despedir': '배웅하다',
    'saludar': '인사하다',
    'presentar': '소개하다',
    'conocer': '만나다',
    'encontrar': '만나다',
    'reunir': '모이다',
    'juntar': '모으다',
    'separar': '헤어지다',
    'partir': '떠나다',
    'marchar': '행진하다',
    'regresar': '돌아가다',
    'volver': '돌아오다',
    'devolver': '돌려주다',
    'entregar': '넘겨주다',
    'prestar': '빌려주다',
    'pedir': '빌리다',
    'rogar': '간청하다',
    'suplicar': '애원하다',
    'exigir': '요구하다',
    'demandar': '요구하다',
    'solicitar': '신청하다',
    'aplicar': '적용하다',
    'usar': '사용하다',
    'utilizar': '이용하다',
    'emplear': '고용하다',
    'contratar': '계약하다',
    'despedir': '해고하다',
    'jubilarse': '은퇴하다',
    'descansar': '휴식하다',
    'relajarse': '쉬다',
    'distraerse': '기분전환하다',
    'concentrarse': '집중하다',
    'esforzarse': '노력하다',
    'luchar': '싸우다',
    'competir': '경쟁하다',
    'ganar': '이기다',
    'perder': '지다',
    'empatar': '비기다',
    'celebrar': '축하하다',
    'festejar': '축제하다',
    'disfrutar': '즐기다',
    'sufrir': '고통받다',
    'doler': '아프다',
    'curar': '치료하다',
    'sanar': '치유하다',
    'mejorar': '좋아지다',
    'empeorar': '악화되다',
    'enfermar': '병들다',
    'morir': '죽다',
    'matar': '죽이다',
    'vivir': '살다',
    'existir': '존재하다',
    'nacer': '태어나다',
    'criar': '기르다',
    'educar': '교육하다',
    'desarrollar': '발달시키다',
    'evolucionar': '진화하다',
    'progresar': '진보하다',
    'avanzar': '전진하다',
    'retroceder': '후퇴하다',
    'parar': '멈추다',
    'continuar': '계속하다',
    'proseguir': '계속하다',
    'interrumpir': '중단하다',
    'pausar': '일시정지하다',
    'reanudar': '재개하다'
}

def get_vocabulary_by_difficulty(difficulty="B2"):
    """난이도별로 어휘를 필터링"""
    if difficulty == "C1":
        # C1 수준: 모든 어휘 포함
        return SPANISH_VOCABULARY
    elif difficulty == "B2":
        # B2 수준: 일부 고급 어휘 제외
        excluded_words = ['coalición', 'constitución', 'fiscal', 'diplomacia', 'embajador', 'refugiado']
        return {k: v for k, v in SPANISH_VOCABULARY.items() if k not in excluded_words}
    else:  # B1
        # B1 수준: 기본 어휘만
        basic_words = ['gobierno', 'política', 'presidente', 'ley', 'trabajo', 'empresa', 'educación', 
                      'salud', 'familia', 'casa', 'comida', 'dinero', 'tiempo', 'país', 'ciudad']
        return {k: v for k, v in SPANISH_VOCABULARY.items() if k in basic_words}

def search_vocabulary(text, difficulty="B2", max_results=5):
    """텍스트에서 해당 난이도의 어휘를 찾아서 반환"""
    vocab_dict = get_vocabulary_by_difficulty(difficulty)
    found_words = []
    
    text_lower = text.lower()
    
    for spanish_word, korean_meaning in vocab_dict.items():
        if spanish_word in text_lower:
            found_words.append(f"{spanish_word} ({korean_meaning})")
            if len(found_words) >= max_results:
                break
    
    return found_words
